GET http://localhost:9000/Galaxy
Accept: application/json

###

POST localhost:9000/Galaxy
Content-Type: application/json

{
  "name": "Orthenis Nebula",
  "description": "Its core consists of a black hole surrounded by colorful stellar debris, and its star systems are scattered far apart, making travel between them long and dangerous. The galaxy is home to ancient, isolated civilizations with mysterious technologies and knowledge.",
  "imagePath": "Orthenis.webp"
}

###

POST localhost:9000/Galaxy/1/planets/3
Content-Type: application/json

{
  "id": 1,
  "name": "string",
  "description": "string",
  "planets": [
    {
      "id": 0,
      "name": "string",
      "description": "string",
      "dateVisited": "2024-09-18T19:54:49.392Z",
      "timesVisited": 0,
      "population": 0,
      "galaxyId": 0,
      "galaxy": {
        "id": 0,
        "name": "string",
        "description": "string",
        "planets": [
          "string"
        ]
      }
    }
  ]
}
