GET http://localhost:9000/Planet
Accept: application/json

###

POST localhost:9000/Planet
Content-Type: application/json

{
  "name": "Veridion",
  "description": "A highly industrialized planet known for its vast factories and production facilities. Veridion is a key economic center in Orthenis Nebula, with towering megacities and sprawling industrial landscapes.",
  "population": 13000000000
}

###