GET http://localhost:9000/Planet
Accept: application/json

###

POST localhost:9000/Planet
Content-Type: application/json

{
  "name": "Elios",
  "description": "A bright, sun-kissed planet orbiting close to a vibrant, young star.",
  "population": 9000000000
}

###